import { useEffect, useState } from 'react';
import { api } from '../api/client';
import { StatusBadge } from '../components/Common';

export default function TasksPage(){
const [tasks,setTasks]=useState([]),[projects,setProjects]=useState([]),[members,setMembers]=useState([]);
const [form,setForm]=useState({project:'',title:'',description:'',assignee:'',status:'To Do',priority:'Medium',dueDate:''});
const [filters,setFilters]=useState({project:'',assignee:'',status:'',priority:''});
const load=()=>{api.get('/tasks',{params:filters}).then(r=>setTasks(r.data));api.get('/projects').then(r=>setProjects(r.data));api.get('/members').then(r=>setMembers(r.data));};useEffect(load,[]);
useEffect(load,[filters.project,filters.assignee,filters.status,filters.priority]);
const submit=async(e)=>{e.preventDefault();await api.post('/tasks',{...form,dueDate:form.dueDate?new Date(form.dueDate).toISOString():undefined,assignee:form.assignee||undefined});setForm({...form,title:'',description:'',dueDate:''});load();};
const changeStatus=async(id,status)=>{const old=tasks.find(t=>t._id===id);await api.put(`/tasks/${id}`,{project:old.project._id,title:old.title,description:old.description,assignee:old.assignee?old.assignee._id:undefined,status,priority:old.priority,dueDate:old.dueDate});load();}
return <div className='space-y-4'><h2 className='text-2xl font-semibold'>Tasks</h2><form onSubmit={submit} className='card grid grid-cols-1 md:grid-cols-4 gap-3'><select className='input' value={form.project} onChange={e=>setForm({...form,project:e.target.value})} required><option value=''>Project</option>{projects.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select><input className='input' placeholder='Title' value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input className='input' placeholder='Description' value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select className='input' value={form.assignee} onChange={e=>setForm({...form,assignee:e.target.value})}><option value=''>Assignee</option>{members.map(m=><option key={m._id} value={m._id}>{m.name}</option>)}</select><select className='input' value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['To Do','In Progress','Review','Done'].map(s=><option key={s}>{s}</option>)}</select><select className='input' value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['Low','Medium','High'].map(s=><option key={s}>{s}</option>)}</select><input className='input' type='date' value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/><button className='btn-primary'>Create Task</button></form>
<div className='card grid md:grid-cols-4 gap-2'>{['project','assignee','status','priority'].map(f=><select key={f} className='input' value={filters[f]} onChange={e=>setFilters({...filters,[f]:e.target.value})}><option value=''>Filter {f}</option>{(f==='project'?projects:f==='assignee'?members:f==='status'?['To Do','In Progress','Review','Done']:['Low','Medium','High']).map(x=><option key={x._id||x} value={x._id||x}>{x.name||x}</option>)}</select>)}</div>
<div className='card overflow-auto'><table className='w-full text-sm'><thead><tr className='border-b text-left'><th>Title</th><th>Project</th><th>Assignee</th><th>Priority</th><th>Due</th><th>Status</th></tr></thead><tbody>{tasks.map(t=><tr key={t._id} className='border-b'><td className='py-2'>{t.title}</td><td>{t.project?.name}</td><td>{t.assignee?.name||'-'}</td><td>{t.priority}</td><td>{t.dueDate?new Date(t.dueDate).toLocaleDateString():'-'}</td><td><select className='input' value={t.status} onChange={e=>changeStatus(t._id,e.target.value)}>{['To Do','In Progress','Review','Done'].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div></div>
}
